- name: Delete Kafka logs
  hosts: kafka_servers
  tasks:
    - name: Run a simple command (command)
      community.docker.docker_container_exec:
       container: kafka1
       command: /bin/bash -c "rm  -rf /kafka-logs/"
       chdir: /root
      register: result

    - name: Print stdout
      ansible.builtin.debug:
        var: result.stdout